In [1]:
import numpy as np

In [2]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [3]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [4]:
#identity matrix

In [16]:
%config Completer.use_jedi = False

In [21]:
np.random.rand(3,3) #every single number has same possibility to be picked

array([[0.30063015, 0.2780462 , 0.95193155],
       [0.01176792, 0.88574998, 0.69716077],
       [0.51170589, 0.12142451, 0.42346858]])

In [24]:
np.random.randn(3,3)
#standard normal distribution,

array([[-1.43150265, -0.01372542, -0.47196722],
       [-0.82211779, -1.03923332, -0.64783775],
       [ 0.65203244, -0.03794094, -1.20634727]])

In [25]:
np.random.randint(1, 100)
#return a random integer from low to high
# in this example,[1,100)

18

In [26]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [27]:
ranarr

array([48, 24, 29, 21, 49, 43,  5, 39,  7, 30])

In [30]:
arr.reshape(5,5)
#reshape(5,4)won't work because 25 cannot be 5*4

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [31]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [32]:
arr.shape
# answer means 25 on 1 axis

(25,)

In [33]:
arr.reshape(5,5).shape

(5, 5)

In [34]:
arr.reshape(25,1).shape

(25, 1)

In [35]:
arr.dtype

dtype('int32')

In [36]:
ranarr

array([48, 24, 29, 21, 49, 43,  5, 39,  7, 30])

In [37]:
ranarr.max()
#ranarr.min()

49

In [38]:
ranarr.argmax()
#return index location of max value
#ranarr.argmin()

4

In [39]:
#Numpy Operations

In [43]:
arr = np.arange(0,10)

In [44]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
arr + arr
# add element by element

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [46]:
arr/arr
#if there's a 0, it cannot be devided

C:\Users\minji\AppData\Local\Temp\ipykernel_17332\2357532307.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [47]:
1/arr
#wont produce error but warning

C:\Users\minji\AppData\Local\Temp\ipykernel_17332\255282349.py:1: RuntimeWarning: divide by zero encountered in true_divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [48]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

In [49]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [50]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [51]:
np.max(arr)

9

In [52]:
arr.max()

9

In [53]:
np.log(arr)
# 0 cannot be logged

C:\Users\minji\AppData\Local\Temp\ipykernel_17332\2332485463.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [54]:
#Np Indexing & Broadcasting

In [61]:
arr = np.arange(0,11)

In [56]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [57]:
arr[8]

8

In [58]:
arr[1:5]

array([1, 2, 3, 4])

In [60]:
arr[0:5] = 100
arr
#Broadcasting

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [62]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [63]:
slice = arr[0:6]

In [64]:
slice[:] = 99

In [65]:
slice

array([99, 99, 99, 99, 99, 99])

In [66]:
arr
#same memory location

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [67]:
arr_copy = arr.copy()
#copy creates new memory

In [68]:
#mat[row,col]
#mat[row][col]


In [69]:
mat = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [70]:
mat

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [72]:
mat[1][1]

25

In [73]:
mat[1,1]

25

In [74]:
mat[:2,1:]

array([[10, 15],
       [25, 30]])

In [75]:
mat[1:,:2]

array([[20, 25],
       [35, 40]])

In [76]:
#Conditional selection

In [77]:
arr = np.arange(1,11)

In [79]:
bool_arr = arr > 4
bool_arr
#get element greater than 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [80]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [81]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

In [82]:
arr[arr <= 9]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [83]:
#Numy exercises review

In [84]:
#Create a 3x3 matrix with value range from 0 to 8
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [85]:
#create 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [89]:
np.random.rand(1)

array([0.22900041])

In [90]:
#array of 25 random numbers sampled from a standard normal distribution
np.random.rand(25)

array([0.53588745, 0.92458103, 0.25056301, 0.96369284, 0.32091181,
       0.45912374, 0.75007075, 0.54132164, 0.07252966, 0.97569889,
       0.31356845, 0.31507732, 0.51395584, 0.11050349, 0.58833763,
       0.09598799, 0.60150547, 0.85370736, 0.50107836, 0.6949737 ,
       0.30145886, 0.30318199, 0.90575481, 0.69847978, 0.6284478 ])

In [91]:
#Create an array of 20 linearly spaced points btw 0 and 1
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [94]:
np.arange(1,101).reshape(10,10)/100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [100]:
mat.sum()
#sums up everything in the matrix

225

In [101]:
#standard deviation
mat.std()

12.909944487358056

In [102]:
mat.sum(axis = 1)
#sum up along the col

array([ 30,  75, 120])

In [103]:
mat

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [104]:
mat.sum(axis = 0)
#sum up along the row

array([60, 75, 90])

In [105]:
np.random.seed(101)
#always get the same random numbers

In [106]:
np.random.rand(1)

array([0.51639863])